version: '3'

services:
 deluge:
  container_name: deluge
  image: kurankat/deluge
  restart: always
  volumes:
   - ./downloads:/downloads
   - ./config:/root/.config/deluge
  environment:
   - TZ=<YOUR TIMEZONE>
  ports:
   - "8112:8112"
   - "58846:58846"
   - "58946:58946"
