version: '3'

services:
  deluge:
    container_name: deluge
    image: kurankat/deluge
    restart: always
    volumes:
      - /local/path/to/downloads:/downloads
      - /local/path/to/config:/root/.config/deluge
    environment:
      - TZ=<YOUR TZ>
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
